import { dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { FlatCompat } from '@eslint/eslintrc'

const compat = new FlatCompat({ baseDirectory: dirname(fileURLToPath(import.meta.url)) })

const config = [
  // next-env.d.ts is generated by the framework on every build; linting it just
  // reports the triple-slash reference Next itself writes there.
  { ignores: ['.next/**', 'node_modules/**', 'qa/**', 'next-env.d.ts'] },
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  {
    rules: {
      /**
       * A handful of marks are rendered as plain <img>: token icons inside an
       * SVG-adjacent layout and inside pills, where next/image's wrapper adds a
       * positioned box that fights the flex alignment for no bandwidth gain —
       * these files are 3–16 KB. Every large asset does go through next/image.
       */
      '@next/next/no-img-element': 'off',
    },
  },
]

export default config
